### ISSUE TITLE
Unhandled Runtime; TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by hemang-h** [CleverProgrammers/opensea-blockchain-youtube#3]
[](https://stackoverflow.com/posts/71012836/timeline)0

On my Localhost:3000, when I am running the code, I am getting an error saying:

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'id')
For the Source part, it is showing a certain section of my code, which is:-

```
    ;(async () => {
  20 |     setSelectedMarketNft(
> 21 |       listings.find((marketNft) => marketNft.asset?.id === selectedNft.id)
     |                                                                       ^
  22 |     )
  23 |   })()
  24 | }, [selectedNft, listings, isListed])
```
There are certain questions of the similar type on stackOverflow, but I am unable to find any answers from any of them. I am making a web3 project, where I am using next.js, sanity and thirweb.

The source code that contains this is:-

```
 const MakeOffer = ({ isListed, selectedNft, listings, marketPlaceModule }) => {
  const [selectedMarketNft, setSelectedMarketNft] = useState()
  const [enableButton, setEnableButton] = useState(false)

  useEffect(() => {
    if (!listings || isListed === 'false') return
    ;(async () => {
      setSelectedMarketNft(
        listings.find((marketNft) => marketNft.asset?.id === selectedNft.id)
      )
    })()
  }, [selectedNft, listings, isListed])

  useEffect(() => {
    if (!selectedMarketNft || !selectedNft) return

    setEnableButton(true)
  }, [selectedMarketNft, selectedNft])
```
This error is happening in the purchase.js file 
![image](https://user-images.githubusercontent.com/73999607/153183114-e79d7a27-aefe-4a7a-bd1a-8d0854945c12.png)

**Comment by trilamanila** [comment]
Had the same error double check [nftId].js make sure it's capital I and everywhere else.

**Comment by hemang-h** [comment]
@trilamanila hmm..I didn't checked like this, but what I did was, I added `if(!selectedNFT)return;` in the `const MakeOffer` and it worked. Yeah, it's true that, now I am getting other errors, but this is one is solved now. 
I don't know if it's gonna work or not! xD
